# Generated by Django 3.2 on 2021-05-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artist_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='album_id',
        ),
    ]
