# Generated by Django 3.2 on 2021-05-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0002_auto_20210501_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='cid',
            field=models.TextField(default=''),
        ),
    ]
