# Generated by Django 3.2 on 2021-05-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0003_alter_artist_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cid',
            field=models.TextField(default='12345'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='cid',
            field=models.TextField(default='12345'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cid',
            field=models.TextField(default='12345'),
        ),
    ]
