# Generated by Django 3.2 on 2021-05-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0004_auto_20210501_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.TextField(),
        ),
    ]
