# Generated by Django 3.2 on 2021-05-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0005_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
