# Generated by Django 3.2 on 2021-05-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi', '0007_auto_20210501_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='times_played',
            field=models.IntegerField(default=0),
        ),
    ]
